FROM golang:1.20 as api-server

RUN mkdir -p /src
WORKDIR /src
COPY . /src
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /api-server ./cmd/api-server

HEALTHCHECK NONE

EXPOSE 80
CMD ["/api-server"]

